### 3 通过主成分分析(PCA)构建情绪指数，阈值（方差解释度）为85%

In [3]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd

Before_PCA = pd.read_excel('Before_PCA.xlsx',index_col = 0)
Before_PCA

001004融资余额（合计，单位：亿元）  001004融券余额（合计，单位：亿元）  001004成交量（单位：亿股）_平滑  \
2012-01-04            363.875206              6.826666            80.739204   
2012-01-05            360.172398              6.868437            87.554887   
2012-01-06            360.680748              6.587964            85.697267   
2012-01-09            357.337918              7.425210            94.374293   
2012-01-10            355.388199              8.156394           111.008693   
...                          ...                   ...                  ...   
2020-12-25          13102.566768           1088.945666           652.047404   
2020-12-28          13136.458941           1096.791430           664.441823   
2020-12-29          13080.194058           1097.484152           659.404614   
2020-12-30          13121.159255           1133.013233           654.358842   
2020-12-31          13117.346750           1161.299899           669.352294   

            001004换手率_平滑  001004市盈率  001004市净率  active index  oversold  \
2012-01-04      0.375522  12.789588   1.809715      0.048000       805   
2012-01-05      0.407417  12.606586   1.783618      0.035429      1564   
2012-01-06      0.411139  12.695395   1.796171      0.043886      1789   
2012-01-09      0.448594  13.078578   1.850566      0.104686      1068   
2012-01-10      0.523940  13.455131   1.903938      0.241829       276   
...                  ...        ...        ...           ...       ...   
2020-12-25      1.173350  21.812183   1.881647      0.249829      2235   
2020-12-28      1.195775  21.800897   1.880798      0.248000      2070   
2020-12-29      1.185581  21.680826   1.870468      0.215543      1968   
2020-12-30      1.175658  21.943651   1.893209      0.246171      2075   
2020-12-31      1.201555  22.350927   1.868283      0.303771      1422   

            001004成交额(单位：亿元)  IPO数量  
2012-01-04        777.539626      0  
2012-01-05        857.911852      0  
2012-01-06        737.341313      3  
2012-01-09       1107.884749      0  
2012-01-10       1629.503664      2  
...                      ...    ...  
2020-12-25       7934.389733      4  
2020-12-28       8807.165381      3  
2020-12-29       8593.905127      1  
2020-12-30       8466.187635      3  
2020-12-31       9613.521721      3  

[2188 rows x 10 columns]

In [4]:
#对x做标准化处理
from sklearn.preprocessing import StandardScaler
Before_PCA_std = StandardScaler().fit_transform(Before_PCA)
Before_PCA_std = pd.DataFrame(Before_PCA_std,index = Before_PCA.index,columns = Before_PCA.columns)
Before_PCA_std

001004融资余额（合计，单位：亿元）  001004融券余额（合计，单位：亿元）  001004成交量（单位：亿股）_平滑  \
2012-01-04             -1.672265             -0.401790            -1.389359   
2012-01-05             -1.673189             -0.401549            -1.359081   
2012-01-06             -1.673062             -0.403167            -1.367333   
2012-01-09             -1.673897             -0.398336            -1.328786   
2012-01-10             -1.674384             -0.394116            -1.254888   
...                          ...                   ...                  ...   
2020-12-25              1.508840              5.842853             1.148656   
2020-12-28              1.517304              5.888129             1.203717   
2020-12-29              1.503253              5.892126             1.181340   
2020-12-30              1.513483              6.097156             1.158924   
2020-12-31              1.512531              6.260391             1.225532   

            001004换手率_平滑  001004市盈率  001004市净率  active index  oversold  \
2012-01-04     -1.185017  -1.245314  -0.117330     -1.685324 -0.060511   
2012-01-05     -1.128044  -1.293555  -0.196141     -1.755875  1.018818   
2012-01-06     -1.121395  -1.270144  -0.158231     -1.708413  1.338777   
2012-01-09     -1.054491  -1.169133   0.006040     -1.367202  0.313486   
2012-01-10     -0.919903  -1.069869   0.167220     -0.597551 -0.812770   
...                  ...        ...        ...           ...       ...   
2020-12-25      0.240114   1.133143   0.099904     -0.552654  1.973006   
2020-12-28      0.280171   1.130168   0.097338     -0.562916  1.738370   
2020-12-29      0.261962   1.098516   0.066142     -0.745067  1.593322   
2020-12-30      0.244237   1.167799   0.134819     -0.573178  1.745480   
2020-12-31      0.290496   1.275162   0.059543     -0.249925  0.816888   

            001004成交额(单位：亿元)     IPO数量  
2012-01-04         -1.192496 -0.568921  
2012-01-05         -1.168674 -0.568921  
2012-01-06         -1.204411  1.427015  
2012-01-09         -1.094581 -0.568921  
2012-01-10         -0.939971  0.761703  
...                      ...       ...  
2020-12-25          0.928822  2.092326  
2020-12-28          1.187516  1.427015  
2020-12-29          1.124305  0.096391  
2020-12-30          1.086449  1.427015  
2020-12-31          1.426523  1.427015  

[2188 rows x 10 columns]

In [40]:
from sklearn.decomposition import PCA
#实例化PCA
pca = PCA()
#训练模型
pca.fit(Before_PCA_std)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [41]:
#PCA后的数据
After_PCA = pd.DataFrame(pca.fit_transform(Before_PCA_std),index = Before_PCA.index,columns = None)
After_PCA

0         1         2         3         4         5  \
2012-01-04 -3.162282  0.552177 -0.866226  0.138985 -0.478135  0.972764   
2012-01-05 -3.131045  1.340202 -0.969928 -0.100773 -0.152310  0.692132   
2012-01-06 -2.839711  1.904575 -0.341932  1.561990  0.527321  0.731455   
2012-01-09 -2.905656  0.607565 -0.862190  0.069541 -0.400595  0.759269   
2012-01-10 -2.404429 -0.411094 -0.113212  1.402698 -0.233321  0.909956   
...              ...       ...       ...       ...       ...       ...   
2020-12-25  3.159719  3.848793  4.384196 -0.217208 -1.375201  1.464032   
2020-12-28  3.217333  3.558806  4.218071 -0.801818 -1.588955  1.549372   
2020-12-29  2.933206  3.321419  3.741310 -1.906160 -2.047640  1.573206   
2020-12-30  3.196152  3.636107  4.342424 -0.808236 -1.753473  1.602039   
2020-12-31  3.443585  2.829718  4.693787 -0.746346 -1.945868  1.791954   

                   6         7         8         9  
2012-01-04 -0.072663  0.279814  0.210512 -0.263425  
2012-01-05 -0.600156  0.198125  0.340975 -0.185057  
2012-01-06 -0.835782  0.102308  0.360172 -0.158660  
2012-01-09 -0.468325  0.231141  0.283380 -0.210282  
2012-01-10 -0.284589  0.216842  0.231063 -0.198298  
...              ...       ...       ...       ...  
2020-12-25 -0.602116 -0.153355 -0.196656  0.024884  
2020-12-28 -0.433546 -0.033613 -0.060872  0.048391  
2020-12-29 -0.262548  0.018673 -0.124666  0.019487  
2020-12-30 -0.481224 -0.062177 -0.133451  0.040021  
2020-12-31 -0.071231  0.137564 -0.065255  0.131367  

[2188 rows x 10 columns]

In [42]:
#计算各自的方差解释度
ratio = pca.explained_variance_ratio_
ratio

array([0.50074351, 0.16932723, 0.11418514, 0.09224581, 0.05308103,
       0.04133633, 0.0155446 , 0.00686573, 0.00546067, 0.00120994])

In [43]:
#计算累计方差解释度
cum_ratio = ratio.cumsum()
cum_ratio

array([0.50074351, 0.67007075, 0.78425589, 0.8765017 , 0.92958272,
       0.97091905, 0.98646366, 0.99332939, 0.99879006, 1.        ])

**如以上结果所示，前4个指标的累计方差解释度满足85%的要求，故n_components = 4**

In [50]:
#调参，重新实例化PCA
pca1 = PCA(n_components = 4)
#训练模型
pca1.fit(Before_PCA_std)

PCA(copy=True, iterated_power='auto', n_components=4, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [53]:
#对Before_PCA_std进行降维
After_PCA_new = pca1.transform(Before_PCA_std)
After_PCA_new = pd.DataFrame(After_PCA_new,index = Before_PCA.index,columns = None)
After_PCA_new.columns = ['first PC','second PC','third PC','fourth PC']
After_PCA_new

first PC  second PC  third PC  fourth PC
2012-01-04 -3.162282   0.552177 -0.866226   0.138985
2012-01-05 -3.131045   1.340202 -0.969928  -0.100773
2012-01-06 -2.839711   1.904575 -0.341932   1.561990
2012-01-09 -2.905656   0.607565 -0.862190   0.069541
2012-01-10 -2.404429  -0.411094 -0.113212   1.402698
...              ...        ...       ...        ...
2020-12-25  3.159719   3.848793  4.384196  -0.217208
2020-12-28  3.217333   3.558806  4.218071  -0.801818
2020-12-29  2.933206   3.321419  3.741310  -1.906160
2020-12-30  3.196152   3.636107  4.342424  -0.808236
2020-12-31  3.443585   2.829718  4.693787  -0.746346

[2188 rows x 4 columns]

In [56]:
# 权重
weight=pca1.explained_variance_ratio_
print(weight)
print(sum(weight))

[0.50074351 0.16932723 0.11418514 0.09224581]
0.8765016974167209


#### 计算综合情绪指数

**注意到以上第一列weight只有0.50074351，采用加权求和**

In [55]:
import numpy as np
#计算第一主成分序列
fpc = []
for i in range(len(After_PCA_new)):
    After_PCA_nums = After_PCA_new.iloc[[i],:]
    fpc += [float(np.dot(After_PCA_nums,weight))]
After_PCA_new['综合情绪指数'] = fpc
After_PCA_new

first PC  second PC  third PC  fourth PC    综合情绪指数
2012-01-04 -3.162282   0.552177 -0.866226   0.138985 -1.576083
2012-01-05 -3.131045   1.340202 -0.969928  -0.100773 -1.460965
2012-01-06 -2.839711   1.904575 -0.341932   1.561990 -0.994427
2012-01-09 -2.905656   0.607565 -0.862190   0.069541 -1.444146
2012-01-10 -2.404429  -0.411094 -0.113212   1.402698 -1.157146
...              ...        ...       ...        ...       ...
2020-12-25  3.159719   3.848793  4.384196  -0.217208  2.714488
2020-12-28  3.217333   3.558806  4.218071  -0.801818  2.621338
2020-12-29  2.933206   3.321419  3.741310  -1.906160  2.282557
2020-12-30  3.196152   3.636107  4.342424  -0.808236  2.637428
2020-12-31  3.443585   2.829718  4.693787  -0.746346  2.670614

[2188 rows x 5 columns]